{% set name = "glew" %}
{% set version = "2.0.0" %}
{% set sha256 = "cc88d2f70a185185eb050eb13789f498425fcd58230bfd65da496b8008f046f2" %}
{% set dev_url = "https://github.com/nigels-com/glew" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.zip
  url: {{ dev_url }}/releases/download/{{ name }}-{{ version }}/{{ name }}-{{ version }}.zip
  sha256: {{ sha256 }}
  patches:
    - CMakeLists.patch  # [win and vc<14]

build:
  number: 1

requirements:
  build:
    # - {{ compiler("c") }}
    # - {{ compiler("cxx") }}
    - cmake
    - pkg-config           # [unix]

# Tests require visual context not present on CIs
test:
  requires:
    # - {{ compiler("c") }}
    # - {{ compiler("cxx") }}
    - cmake
  commands:
    - test -f $PREFIX/include/GL/glew.h  # [unix]
    - if not exist %LIBRARY_INC%\GL\glew.h exit 1  # [win]

about:
  home: http://glew.sourceforge.net/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: "The OpenGL Extension Wrangler Library"
  description: |
    The OpenGL Extension Wrangler Library (GLEW) is a cross-platform open-source C/C++
    extension loading library. GLEW provides efficient run-time mechanisms for determining
    which OpenGL extensions are supported on the target platform. OpenGL core and extension
    functionality is exposed in a single header file.
  doc_url: http://glew.sourceforge.net/basic.html
  dev_url: {{ dev_url }}

extra:
  recipe-maintainers:
    - v-turin
